### ISSUE TITLE
MS1 AMT and HAMT Proof Generation

### ISSUE THREAD

**Issue by mattsse** [ChainSafe/filecoindot#1]
## Implementation details

Add a seprate crate for AMT and HAMT Proof support:
- [x] proof generation and verification
- [x] reconstruct the root hash given a message/state entry and a proof 

## Testing details

- [x] works in wasm
## Acceptance Criteria

- [x] construct a block inclusion proof for any valid Filecoin message, receipt or state entry
- [ ] test suite covers required use-cases for proof verification
